FILES_TO_RM = \
	BarOraculo.txt \
	Isla_de_las_Estrellas.txt \
	Isla_de_los_Susurros.txt \
	Isla_del_Bosque_Encantado.txt \
	Isla_del_Dragon_Rojo.txt \
	Isla_del_Tesoro_Oculto.txt \
	Isla_del_Trueno.txt \
	Isla_de_las_Sombras.txt \
	Salida.txt

default:
	@echo "@ Para borrar todos los archivos .txt relativos al problema debes ejecutar make clean"

clean:
	@echo "@ Borrando todos los .txt de esta carpeta"
	@rm -f $(FILES_TO_RM)
	@echo "@ Archivos borrados satisfactoriamente"